general:
  project_name: tf_flowers
  logs_dir: logs
  saved_models_dir: saved_models
  display_figures: True
  global_seed: 123

operation_mode: chain_tqeb

dataset:
  name: flowers
  class_names: [daisy, dandelion, roses, sunflowers, tulips]
  training_path: ./datasets/flower_photos
  validation_split: 0.2
  quantization_path: ./datasets/flower_photos
  quantization_split: 0.1
  check_image_files: False
  seed: 127

preprocessing:
  rescaling: { scale: 1/255.0, offset: 0.0 }
  resizing:
    interpolation: nearest
    aspect_ratio: fit
  color_mode: rgb

training:
  model:
    name: squeezenet
    version: v1.1
    input_shape: (64, 64, 3)
  dropout: 0.3
  batch_size: 64
  epochs: 52
  optimizer:
    Adam:
      learning_rate: 0.001
  callbacks:
    ReduceLROnPlateau:
      monitor: val_accuracy
      mode: max
      factor: 0.5
      patience: 40
      min_lr: 1.0e-05
    EarlyStopping:
      monitor: val_accuracy
      mode: max
      restore_best_weights: true
      patience: 60

quantization:
  quantizer: TFlite_converter
  quantization_type: PTQ
  quantization_input_type: int8
  quantization_output_type: int8
  granularity: per_channel
  optimize: True
  export_dir: quantized_models

prediction:
  test_files_path: ./datasets/flower_photos/daisy

tools:
  stedgeai:
    version: 10.2.0
    optimization: balanced
    on_cloud: True
  path_to_cubeIDE: C:/ST/STM32CubeIDE_<*.*.*>/STM32CubeIDE/stm32cubeide.exe

benchmarking:
  board: NUCLEO-F446RE

deployment:
  c_project_path: ../application_code/image_classification/STM32F4
  IDE: GCC
  verbosity: 1
  hardware_setup:
    serie: STM32F4
    board: NUCLEO-F446RE

mlflow:
  uri: ./src/experiments_outputs/mlruns

hydra:
  run:
    dir: ./src/experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}
